### ISSUE TITLE
Installation problem of pyexifinfo

### ISSUE THREAD

**Issue by pinli111** [guinslym/pyexifinfo#11]
Hi, I saw previous post had mentioned about pyexifinfo problem and I had tried the solution which is "pip install -i https://testpypi.python.org/pypi pyexifinfo"
However, there is still an error of _FileNotFoundError: [WinError 2] The system cannot find the file specified._
And there is a red line of Command "python setup.py egg_info" failed with error code 1 in C:\Users\USER~1\AppData\Local\Temp\pip-install-jhx_uai0\pyexifinfo\
Can I know why does it happen? How should I solve it?
(PS: I am using python 3.7)

**Comment by fa7al** [comment]
And resolution to this issue?

**Comment by Ganofins** [comment]
> Hi, I saw previous post had mentioned about pyexifinfo problem and I had tried the solution which is "pip install -i https://testpypi.python.org/pypi pyexifinfo"
> However, there is still an error of _FileNotFoundError: [WinError 2] The system cannot find the file specified._
> And there is a red line of Command "python setup.py egg_info" failed with error code 1 in C:\Users\USER~1\AppData\Local\Temp\pip-install-jhx_uai0\pyexifinfo
> Can I know why does it happen? How should I solve it?
> (PS: I am using python 3.7)

install [exiftool](https://exiftool.org/Image-ExifTool-12.02.tar.gz)

**Comment by vascospooren** [comment]
I installed exiftool and I'm still having the error...
Someone any fix?
```
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```
