### ISSUE TITLE
Custom Exception for exiftool not installed

### ISSUE THREAD

**Issue by AbdealiLoKo** [guinslym/pyexifinfo#4]
Hi !

I am making a tool for wikipedia-commons and wanted to use exiftool in python and came across this awesome library.
I found that it worked well, but there is no good exception handling is exiftool is not installed.

Possible improvements:
- Custom Exception being thrown if exiftool is not in PATH (Currently it gives an OSError)
- Making a function to check if exiftool is installed `pyexifinfo.check_deps()` ?

**Comment by guinslym** [comment]
Thanks @AbdealiJK! I added a function in the setup.py so that it won't installed pyExifInfo if Exiftool is not installed

**Comment by AbdealiLoKo** [comment]
Thanks a lot :)
