### ISSUE TITLE
RUnning on directories

### ISSUE THREAD

**Issue by AbdealiLoKo** [guinslym/pyexifinfo#5]
When I run pyexiftool on directories, it gives an unexpected output:

```
In [75]: pyexifinfo.get_json('.')
    1 directories scanned
    0 image files read
Out[75]: '/home/ajk/Documents/'
```

So, it prints `1 directories scanned` to stdout and returns back the directory name

**Comment by guinslym** [comment]
I added this Exception now
**ValueError: The filename given was either non existent or was a directory**

Thanks @AbdealiJK
