### ISSUE TITLE
Return value for some files

### ISSUE THREAD

**Issue by AbdealiLoKo** [guinslym/pyexifinfo#6]
For some files which have the "error" value, the output is unexpected. Running exiftool gives:

```
$ exiftool -G -j -sort ./LICENSE 
[{
  "SourceFile": "./LICENSE",
  "ExifTool:Error": "Unknown file type",
  "ExifTool:ExifToolVersion": 9.46,
  "File:Directory": ".",
  "File:FileAccessDate": "2016:05:04 14:03:29+05:30",
  "File:FileInodeChangeDate": "2016:03:18 08:41:17+05:30",
  "File:FileModifyDate": "2016:03:18 08:41:17+05:30",
  "File:FileName": "LICENSE",
  "File:FilePermissions": "rw-rw-r--",
  "File:FileSize": "1076 bytes"
}]
```

But pyexifinfo gives:

```
In [76]: pyexifinfo.get_json('./LICENSE')
Out[76]: '/home/ajk/Documents/wiki/LICENSE'
```

It makes a lot of sense to show the output given by exiftool in such cases because it has meaningful data and an error message !

**Comment by guinslym** [comment]
hi @AbdealiJK! 
on my side it's work fine

`>>> filename = 'LICENSE'

> > > p.get_json(filename)
> > > [{u'File:FilePermissions': u'rw-rw-r--', u'File:FileType': u'M2TS', u'File:FileSize': u'18 kB', u'SourceFile': u'/h
> > > ome/guinsly/development/public/project/sugbox/totrash/pyexifinfo/LICENSE', u'File:FileInodeChangeDate': u'2016:05:0
> > > 5 21:20:07-04:00', u'File:MIMEType': u'video/m2ts', u'File:FileAccessDate': u'2016:05:05 21:20:10-04:00', u'ExifToo
> > > l:Warning': u'Synchronization error', u'File:FileModifyDate': u'2016:05:05 21:20:07-04:00', u'ExifTool:ExifToolVers
> > > ion': 9.46, u'File:Directory': u'/home/guinsly/development/public/project/sugbox/totrash/pyexifinfo', u'File:FileNa
> > > me': u'LICENSE'}]
> > > p.get_json('./LICENSE')
> > > [{u'File:FilePermissions': u'rw-rw-r--', u'File:FileType': u'M2TS', u'File:FileSize': u'18 kB', u'SourceFile': u'/h
> > > ome/guinsly/development/public/project/sugbox/totrash/pyexifinfo/LICENSE', u'File:FileInodeChangeDate': u'2016:05:0
> > > 5 21:20:07-04:00', u'File:MIMEType': u'video/m2ts', u'File:FileAccessDate': u'2016:05:05 21:20:10-04:00', u'ExifToo
> > > l:Warning': u'Synchronization error', u'File:FileModifyDate': u'2016:05:05 21:20:07-04:00', u'ExifTool:ExifToolVers
> > > ion': 9.46, u'File:Directory': u'/home/guinsly/development/public/project/sugbox/totrash/pyexifinfo', u'File:FileNa
> > > me': u'LICENSE'}]
> > > `
