### ISSUE TITLE
Installation problem?

### ISSUE THREAD

**Issue by dtougas** [guinslym/pyexifinfo#7]
When I try to install this using pip, the installation appears to go smoothly, but the pyexifinfo library is not actually installed in the site-packages directory. The dist-info file is created, but not the actually python package. FWIW, this is on FreeBSD 10.3, Python 2.7.11, and PIP 8.1.1 in a virtual environment.

**Comment by guinslym** [comment]
Thanks @dtougas for this finding.  Its weird but meanwhile I'm working to resolve this issue.

For the moment could you try
`pip install -i https://testpypi.python.org/pypi pyexifinfo` this will installed it from the pypi test server. Then cd into your python package folder:

`cd /usr/local/lib/python2.7/dist-packages` and check to see if you  have a **pyexifinfo** folder in this directory. 

`tree pyexifinfo` 

```
pyexifinfo/
├── __init__.py
├── __pycache__
│   ├── __init__.cpython-34.pyc
│   └── pyexifinfo.cpython-34.pyc
└── pyexifinfo.py
```

Run python 
`bpython -q`
`import pyexifinfo`

a+

**Comment by guinslym** [comment]
Problem corrected! Thanks ! merci

**Comment by guinslym** [comment]
Yes you right @dtougas your issue did occurred one more time while installing the package on one of my server. I figured out that I didn't include this line in the setup.py `packages=['pyexifinfo'],`

Thanks 
Problem resolved

**Comment by dtougas** [comment]
Thanks for the update! I haven't tried this since I reported the problem, as I was in a bit of a hurry and so decided to use a different package instead. I will take another look when I get some time.
